chat/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
# basic securit for password
from werkzeug.security import check_password_hash, generate_password_hash
#import db with models in order to get data
from chat.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        nickname = request.form['nickname']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not nickname:
            error = 'Nickname is required.'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    "INSERT INTO user (nickname, username, password) VALUES (?, ?, ?)",
                    (nickname, username, generate_password_hash(password)),
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered.\n Nick {nickname} is unavaliable"
            else:
                return redirect(url_for("auth.login"))

        flash(error)
    # render_template('template_path in templates folder') 
    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()

@bp.route('/logout')
def logout():
    session.clear()
    # url_for() built in func to redirect
    return redirect(url_for('index'))

# custom function can be imported and used as decorator
# @login_required 
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

chat/templates/base.html
<!doctype html>

<head>
  <title>{% block title %}{% endblock %} - Flaskr</title>
  <!--<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"> --->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body class="bg-secondary">
  <!--
  
  <nav class="navbar navbar-scroll navbar-dark bg-primary">
    <div class="container-fluid flex-row">
      <a class="navbar-brand" href="{{ url_for('conv.index') }}">
        <h1>Flaskr</h1>
      </a>
      <ul>
        {% if g.user %}
        <li class="nav-item"><span>{{ g.user['username'] }}</span>
          <li class="nav-item"><span>{{ g.user['id'] }}</span>
            <li class="nav-item"><a href="{{ url_for('auth.logout') }}">Log Out</a>
              {% else %}
              <li class="nav-item"><a href="{{ url_for('auth.register') }}">Register</a>
                <li class="nav-item"><a href="{{ url_for('auth.login') }}">Log In</a>
                  {% endif %}
                </ul>
              </div>
            </nav>
            
          -->
  <nav class="navbar navbar-expand sticky-top navbar-stick-top bg-secondary">
    <div class="container container-fluid">
      <a class="navbar-brand" href="{{ url_for('conv.index') }}">
        <h1>CHAT✉</h1>
      </a>
      <div class="d-flex flex-row-reverse">
        <ul class="navbar-nav">
          {% if g.user %}
          <li class="nav-item">
            <a class="nav-link disabled" aria-current="page" href="#">{{ g.user['username'] }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">{{ g.user['id'] }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.logout') }}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.register') }}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.login') }}">Log In</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>


  <div class="container">
    <header>
      {% block header %}{% endblock %}
    </header>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}

  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script>
    const form = document.getElementsByTagName('form');
    console.log(form);
    form[0].addEventListener('onload', function handleSubmit(event) {
      event.preventDefault();

      form[0].reset();
    });

  </script>
</body>